project:
  type: book

book:
  title: "Time Series Forecasting"
  subtitle: "ITESO"
  author: "Pablo Benavides-Herrera"
  date: "17/6/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



